#travis configuration for coverage testing
language: 
  - java
#sudo: false # only for faster builds

install:
- cd ${TRAVIS_BUILD_DIR}
# install latest LCOV (1.9 was failing for me) [1]

- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install
- sudo apt update && sudo apt install python3-cryptography
- python -m pip install ansible==2.10.3 
- pip3 install cryptography

# install lcov to coveralls conversion + upload tool
- gem install coveralls-lcov


before_script: 
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters

# Compiler selection
compiler:
  - gcc
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - make && ./test-library.out
# stages:
#   - build 
#   - test

_shared_job: &shared_job
  script: echo "shared script config"
jobs:
  include:
  - name: Job 1
    <<: *shared_job
  - name: Job 2
    <<: *shared_job

# jobs:
#   include:
#     - stage: build
#       # Build step
#       os: linux-ppc64le
#       language: python
#       python:
#         - "3.6"
#       dist: bionic
#       env:
#         - name= "build on power"
#         - ARCH=ppc64le
#         - ARCH_STRING="-ppc64le"
#     - stage: build
#       script:
#         - mkdir hari
#       language: python
#       python:
#         - "3.6"
#     - stage: test
#       script:
#         - echo "testing for multi arcch"

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
#- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
- coveralls-lcov  coverage.info #for open source 
